set nu
set shiftwidth=4
set smartindent
set tabstop=4
set rnu
set autoindent
set scrolloff=8
set wildmenu
set wildmode=list:longest
set cursorline
syntax on
colorscheme seoul256
set background=dark
inoremap jj <Esc>
inoremap ` <c-n>
inoremap ( ()<Left>
inoremap [ []<Left>
